---
title: "openHDF5"
author: "Henry Senyondo"
date: "June 20, 2016"
output: html_document
---


## About this code
```{r Load-libraries}
# load libraries

library(raster)
library(rhdf5)
library(rgdal)

```

## lets open a file
```{r select-file}
# Load 

f <-"../NEONdata/D17-California/TEAK/2013/spectrometer/reflectance/Subset3NIS1_20130614_100459_atmcor.h5"

#view h5 structure

h5ls(f)

```


## Import lots of spacial Information
```{r}

```



```
mapInfo <- h5read(f,"map info", read.attributes = TRUE)
mapInfo

```

## grab Reflectance Metadata

```{r get-refl-metadata}

# read in the reflectance data attributes
reflInfo <- h5readAttributes(file = f, name = "Reflectance")

reflInfo

# define scale factor
scaleFactor <- reflInfo$'Scale factor'

# define no data value
noDataValue <- as.numeric(reflInfo$`data ignore value`)
str(noDataValue)

```


## import  Datat Dims

```{r imports-dims}

# open dile for viewing
fid <- H5Fopen(f)

# open / connect to the reflectance data
did <- H5Dopen(fid, 'Reflectance')
did

# grab tge data set dimensiobs
sid <- H5Dget_space(did)
dims <- H5Sget_simple_extent_dims(sid)$size
dims

#close all open connections
H5Sclose(sid)
H5Dclose(did)
H5Fclose(fid)

```


```{r read-data}

# extract slice of H5 file
b56 <- h5read(f, "Reflectance", 
              index =  list(1:dims[1], 1:dims[2],56))


class(b56)
```


#3 convert data to Matrix

```{r convert-matrix}
b56 <- b56[,,1]

# lets plot some data Finally
image(b56)

image(log(b56),main="log tranformed data")

hist(b56)
```



## Time to clean up data

```{r data-clean-up }
# assign no data values to objects
b56[b56 == noDataValue] <- NA

b56 <- b56/scaleFactor
hist(b56)
```


## transpose Data

```{r transpose-date }

# transpose the data
b56 <- t(b56)
image(log(b56))

```


## create special Extent

```{r create-special-extent }

# split ut Mao infor object
mapInfo <- strsplit(mapInfo,",")
mapInfo <- unlist(mapInfo)
mapInfo


# Defining the upper left hand conner coordinate
xMin <- as.numeric(mapInfo[4])
yMax <- as.numeric(mapInfo[5])



# get spacial resolution
xres  <- as.numeric(mapInfo[6])
yres  <- as.numeric(mapInfo[7])


#calculate XMax and YMin
xMax <- xMin +  dims[1] * xres
yMin <- yMax - dims[2] * yres


```

# Create extent object 
```{r create-extent }
rasExt <- extent(xMin, xMax, yMin, yMax)
rasExt

```





## Load package Code


```{r createstacks}

# install devtools
# install.packages("devtools")
library(devtools)

# install_github("lwasser/neon-aop-package/neonAOP")
library(neonAOP)
# use open band function to view data
b55 <- open_band(f,
                 bandNum = 55,
                 epsg = 32611)
b55
# plot data
plot(b55)

# define code
epsg <- 32611
# import several bands
bands <- c(58, 34, 19)

# create raster stack
RGBStack <- create_stack(f,
                          bands=bands,
                         epsg=epsg)
RGBStack

plot(RGBStack)

# plot RGB image
plotRGB(RGBStack,
        stretch='lin')

# cir image
bands <- c(90, 34, 19)

CIRStack <- create_stack(f,
                          bands=bands,
                         epsg=epsg)

plotRGB(CIRStack,
        stretch='lin')
                   
```